language: c

git:
  depth: 1500

compiler:
  - gcc
  - clang

env:
  - MAKE_CHECK="nonroot"
  - MAKE_CHECK="root"
  - MAKE_CHECK="dist"

branches:
  only:
    - master
    - /^stable.*/

install:
  # install some packages from Ubuntu's default sources
  - sudo apt-get -qq update
  - sudo apt-get install -qq
    bc
    dnsutils
    libcap-ng-dev
    libpam-dev
    libudev-dev
    gtk-doc-tools
    ntp

before_script:
  - source ./.travis-functions.sh
  - travis_before_script

script:
  - travis_script

after_script:
  - travis_after_script

before_install:
  - $CC --version
  - which $CC
  # workaround clang not system wide, fail on sudo make install
  - export CC=`which $CC`
